### ISSUE TITLE
any code on this?

### ISSUE THREAD

**Issue by liamxg** [waleedgeo/30daymap-2023#1]
@waleedgeo

**Comment by waleedgeo** [comment]
Dear Liam,
There are codes, datasets, and Project files available, but due to unavailability of time, I cannot structure them. They are all scattered as I am busy with creating one map each day.

I plan to upload all extra files finalized after the end of this event (hopefully).
However, if it's urgent, you can request the specific part, and I will try my best to provide it.

**Comment by liamxg** [comment]
@waleedgeo thanks for your reply, I want to know this one please:
<img width="865" alt="image" src="https://github.com/waleedgeo/30daymap-2023/assets/46078579/40bcc1ca-5c1e-40af-8eac-c96745099565">

**Comment by liamxg** [comment]
i want to make a gif for this, through time.

**Comment by waleedgeo** [comment]
Nice idea,

you can find the data here [Link](https://data.humdata.org/dataset/global-active-archive-of-large-flood-events-dfo) and then can process it in any GIS software. For this map I did not use any code. Just download data, import into GIS software and create final map using Illustrator.

**Comment by liamxg** [comment]
cool! I thought you using R for your plot, I am wrong. I will try to plot it in R. Thanks for your tips. Cheers.

**Comment by liamxg** [comment]
any data for 2011-2023? @waleedgeo

**Comment by waleedgeo** [comment]
Yes you can find flood locations from 1985 to 2016 from this dataset: https://gee-community-catalog.org/projects/flood/

Please share with me the final results, when you finished your visualization.
